# Generated by Django 5.2.7 on 2025-10-18 18:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0022_alter_priceadjustmentitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em contagem'), ('closed', 'Fechado')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_closed', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_started', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade congelada')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantidade contada')),
                ('final_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantidade final')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Registrado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estoque.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Item de inventário',
                'verbose_name_plural': 'Itens de inventário',
                'ordering': ('product__name',),
                'unique_together': {('inventory', 'product')},
            },
        ),
    ]
