# Generated by Django 5.2.7 on 2025-10-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('products', '0022_alter_priceadjustmentitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='filter_below_min_stock',
            field=models.BooleanField(default=False, verbose_name='Somente abaixo do estoque mínimo'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='filter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_filters', to='products.productgroup', verbose_name='Grupo de produtos'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='filter_in_stock_only',
            field=models.BooleanField(default=False, verbose_name='Somente produtos com estoque'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='filter_query',
            field=models.CharField(blank=True, max_length=255, verbose_name='Filtro por texto'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='filter_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_filters', to='products.productsubgroup', verbose_name='Subgrupo de produtos'),
        ),
    ]
