# Generated by Django 5.2.7 on 2025-10-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_inventory_filter_below_min_stock_and_more'),
        ('products', '0022_alter_priceadjustmentitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_entries', to='estoque.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_selections', to='products.product')),
            ],
            options={
                'verbose_name': 'Produto selecionado',
                'verbose_name_plural': 'Produtos selecionados',
                'unique_together': {('inventory', 'product')},
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='selected_products',
            field=models.ManyToManyField(blank=True, related_name='selected_inventories', through='estoque.InventorySelection', to='products.product'),
        ),
    ]
