# Generated by Django 5.2.7 on 2025-10-18 20:51

import django.db.models.deletion
from django.db import migrations, models


def assign_inventory_company(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    Inventory = apps.get_model('estoque', 'Inventory')

    company = Company.objects.filter(is_active=True).order_by('id').first() or Company.objects.order_by('id').first()
    if not company:
        return

    Inventory.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_default_discount_percent_and_more'),
        ('estoque', '0003_inventoryselection_inventory_selected_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='companies.company'),
        ),
        migrations.RunPython(assign_inventory_company, migrations.RunPython.noop),
    ]
