# Generated by Django 5.2.7 on 2025-11-06 11:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_inventoryitem_recount_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=20, verbose_name='Código do produto')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('loja', models.CharField(max_length=10, verbose_name='Loja')),
                ('local', models.CharField(max_length=10, verbose_name='Local')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=15, verbose_name='Quantidade')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item do coletor de inventário',
                'verbose_name_plural': 'Itens do coletor de inventário',
                'ordering': ('loja', 'local', 'codigo_produto'),
                'unique_together': {('codigo_produto', 'loja', 'local')},
            },
        ),
    ]
