# Generated by Django 5.2.7 on 2025-11-06 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_collectorinventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorinventoryitem',
            name='contagens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=15), blank=True, default=list, size=None, verbose_name='Contagens registradas'),
        ),
    ]
