# Generated by Django 5.2.7 on 2025-11-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_collectorinventoryitem_contagens'),
        ('products', '0025_product_cost_price_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorinventoryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_inventory_items', to='products.product', verbose_name='Produto associado'),
        ),
        migrations.AlterField(
            model_name='collectorinventoryitem',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
    ]
