# Generated by Django 5.2.7 on 2025-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_collectorinventoryitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorinventoryitem',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em'),
        ),
    ]
