# Generated by Django 5.2.7 on 2025-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_collectorinventoryitem_fechado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorinventoryitem',
            name='plu_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código PLU'),
        ),
    ]
