# Generated by Django 5.2.7 on 2025-10-16 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SefazConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, verbose_name='URL base da SEFAZ')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='Token de acesso')),
                ('timeout', models.PositiveIntegerField(default=10, verbose_name='Timeout (segundos)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração SEFAZ',
                'verbose_name_plural': 'Configuração SEFAZ',
            },
        ),
    ]
