# Generated by Django 5.2.7 on 2025-10-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_code_cnpj'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_products', models.BooleanField(default=True, verbose_name='Produtos')),
                ('can_manage_clients', models.BooleanField(default=True, verbose_name='Clientes')),
                ('can_manage_sales', models.BooleanField(default=True, verbose_name='Vendas')),
                ('can_manage_purchases', models.BooleanField(default=True, verbose_name='Compras')),
                ('can_manage_finance', models.BooleanField(default=True, verbose_name='Financeiro')),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('companies', models.ManyToManyField(blank=True, related_name='access_profiles', to='companies.company', verbose_name='Empresas permitidas')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de acesso',
                'verbose_name_plural': 'Perfis de acesso',
                'ordering': ('user__username',),
            },
        ),
    ]
