# Generated by Django 5.2.7 on 2025-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessprofile',
            name='can_create_sales_records',
            field=models.BooleanField(default=True, verbose_name='Criar vendas e orçamentos'),
        ),
        migrations.AddField(
            model_name='useraccessprofile',
            name='can_delete_sales_records',
            field=models.BooleanField(default=True, verbose_name='Excluir vendas e orçamentos'),
        ),
        migrations.AddField(
            model_name='useraccessprofile',
            name='can_edit_sales_records',
            field=models.BooleanField(default=True, verbose_name='Editar vendas e orçamentos'),
        ),
    ]
