# Generated by Django 5.2.7 on 2025-10-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useraccessprofile_can_create_sales_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessprofile',
            name='can_view_all_companies',
            field=models.BooleanField(default=False, verbose_name='Visualiza todas as empresas'),
        ),
    ]
