# Generated by Django 5.2.7 on 2025-10-19 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useraccessprofile_can_view_all_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='Usuário SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='Senha SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='SMTP com STARTTLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='SMTP com SSL')),
                ('default_from_email', models.EmailField(blank=True, max_length=254, verbose_name='Remetente padrão')),
                ('incoming_protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', max_length=10, verbose_name='Protocolo de recebimento')),
                ('incoming_host', models.CharField(blank=True, max_length=255, verbose_name='Servidor de entrada')),
                ('incoming_port', models.PositiveIntegerField(default=993, verbose_name='Porta de entrada')),
                ('incoming_username', models.CharField(blank=True, max_length=255, verbose_name='Usuário de entrada')),
                ('incoming_password', models.CharField(blank=True, max_length=255, verbose_name='Senha de entrada')),
                ('incoming_use_ssl', models.BooleanField(default=True, verbose_name='Recebimento com SSL/TLS')),
                ('incoming_use_tls', models.BooleanField(default=False, verbose_name='Recebimento com STARTTLS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de e-mail',
                'verbose_name_plural': 'Configurações de e-mail',
            },
        ),
    ]
