# Generated by Django 5.2.7 on 2025-10-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto do perfil'),
        ),
        migrations.AddField(
            model_name='useraccessprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome para exibição'),
        ),
        migrations.AddField(
            model_name='useraccessprofile',
            name='interface_font_size',
            field=models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], default='medium', max_length=20, verbose_name='Tamanho da fonte'),
        ),
    ]
