# Generated by Django 5.2.7 on 2025-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates', verbose_name='Certificado digital A1 (PFX/P12)'),
        ),
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Senha do certificado'),
        ),
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_serial_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Número de série'),
        ),
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Proprietário do certificado'),
        ),
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado enviado em'),
        ),
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado válido a partir de'),
        ),
        migrations.AddField(
            model_name='sefazconfiguration',
            name='certificate_valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado válido até'),
        ),
    ]
