# Generated by Django 5.2.7 on 2025-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sefazconfiguration_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefazconfiguration',
            name='environment',
            field=models.CharField(choices=[('production', 'Produção'), ('homologation', 'Homologação')], default='production', max_length=20, verbose_name='Ambiente SEFAZ'),
        ),
    ]
