# Generated by Django 5.2.7 on 2025-10-16 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('entry_type', models.CharField(choices=[('receivable', 'Receber'), ('payable', 'Pagar')], default='receivable', max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('paid', models.BooleanField(default=False, verbose_name='Liquidado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lançamento financeiro',
                'verbose_name_plural': 'Lançamentos financeiros',
                'ordering': ('-due_date', '-created_at'),
            },
        ),
    ]
