# Generated by Django 5.2.7 on 2025-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20251224_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='loja_codigo',
            field=models.CharField(default='00001', max_length=10, verbose_name='Loja'),
        ),
    ]
