# Generated by Django 5.2.7 on 2026-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_erp_lojas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoSync',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_column='DescricaoCompleta', null=True)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=100, null=True)),
                ('secao', models.CharField(blank=True, db_column='Secao', max_length=20, null=True)),
                ('grupo', models.CharField(blank=True, db_column='Grupo', max_length=20, null=True)),
                ('subgrupo', models.CharField(blank=True, db_column='Subgrupo', max_length=20, null=True)),
                ('unidade', models.CharField(blank=True, db_column='Unidade', max_length=20, null=True)),
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=50, null=True)),
                ('plu', models.CharField(blank=True, db_column='PLU', max_length=50, null=True)),
                ('preco_normal', models.DecimalField(blank=True, db_column='PrecoNormal', decimal_places=2, max_digits=18, null=True)),
                ('preco_promocional_1', models.DecimalField(blank=True, db_column='PrecoPromocional1', decimal_places=2, max_digits=18, null=True)),
                ('preco_promocional_2', models.DecimalField(blank=True, db_column='PrecoPromocional2', decimal_places=2, max_digits=18, null=True)),
                ('estoque_disponivel', models.DecimalField(blank=True, db_column='EstoqueDisponivel', decimal_places=2, max_digits=18, null=True)),
                ('loja', models.CharField(blank=True, db_column='Loja', max_length=20, null=True)),
                ('ref_plu', models.CharField(blank=True, db_column='REFPLU', max_length=50, null=True)),
                ('row_hash', models.TextField(blank=True, db_column='RowHash', null=True)),
            ],
            options={
                'db_table': 'vw_produtos_sync_preco_estoque',
                'managed': False,
            },
        ),
    ]
