# Generated by Django 5.2.7 on 2025-10-18 20:51

import django.db.models.deletion
from django.db import migrations, models


def assign_purchase_company(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    PurchaseOrder = apps.get_model('purchases', 'PurchaseOrder')

    company = Company.objects.filter(is_active=True).order_by('id').first() or Company.objects.order_by('id').first()
    if not company:
        return

    PurchaseOrder.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_default_discount_percent_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company'),
        ),
        migrations.RunPython(assign_purchase_company, migrations.RunPython.noop),
    ]
