# Generated by Django 5.2.7 on 2025-10-16 00:00

from django.db import migrations, models
import django.utils.timezone


def populate_client_documents(apps, schema_editor):
	Client = apps.get_model('clients', 'Client')
	for client in Client.objects.all().order_by('pk'):
		document = ''.join(ch for ch in (getattr(client, 'document', '') or '') if ch.isdigit())
		if len(document) == 14:
			person_type = 'J'
		elif len(document) == 11:
			person_type = 'F'
		else:
			person_type = 'F'
			document = f"{client.pk:011d}"[-11:]
		client.person_type = person_type
		client.document = document
		client.code = document
		client.save(update_fields=['person_type', 'document', 'code'])


class Migration(migrations.Migration):

	dependencies = [
		('clients', '0002_trigram_indexes'),
	]

	operations = [
		migrations.AddField(
			model_name='client',
			name='person_type',
			field=models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de pessoa'),
		),
		migrations.AddField(
			model_name='client',
			name='document',
			field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ'),
		),
		migrations.AddField(
			model_name='client',
			name='code',
			field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código'),
		),
		migrations.AddField(
			model_name='client',
			name='updated_at',
			field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Atualizado em'),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='client',
			name='first_name',
			field=models.CharField(max_length=150, verbose_name='Nome / Razão social'),
		),
		migrations.AlterField(
			model_name='client',
			name='last_name',
			field=models.CharField(blank=True, max_length=150, verbose_name='Sobrenome / Nome fantasia'),
		),
		migrations.RunPython(populate_client_documents, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='client',
			name='document',
			field=models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ'),
		),
		migrations.AlterField(
			model_name='client',
			name='code',
			field=models.CharField(max_length=14, unique=True, verbose_name='Código'),
		),
	]
