# Generated by Django 5.2.7 on 2025-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_add_loja_codigo_to_clientes_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSync',
            fields=[
                ('cliente_codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cliente_status', models.IntegerField(blank=True, null=True)),
                ('cliente_razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_cnpj_cpf', models.CharField(blank=True, max_length=32, null=True)),
                ('cliente_tipo_pf_pj', models.CharField(blank=True, max_length=4, null=True)),
                ('cliente_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_uf', models.CharField(blank=True, max_length=5, null=True)),
                ('cliente_cep', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_telefone1', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_telefone2', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_email', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_inscricao_municipal', models.CharField(blank=True, max_length=50, null=True)),
                ('vendedor_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('vendedor_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_venda_data', models.DateTimeField(blank=True, null=True)),
                ('ultima_venda_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loja_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'erp_clientes_vendedores_view',
                'ordering': ('cliente_razao_social', 'cliente_codigo'),
                'managed': False,
            },
        ),
    ]
