# Generated by Django 5.2.7 on 2025-10-16 11:07

from django.db import migrations, models


def populate_company_codes(apps, schema_editor):
	Company = apps.get_model('companies', 'Company')
	for company in Company.objects.all():
		raw_tax_id = (company.tax_id or '').strip()
		if raw_tax_id:
			code = ''.join(ch for ch in raw_tax_id if ch.isalnum())
		else:
			code = f"EMP{company.pk}"
		base_code = code[:27]  # reserve space for suffix if needed
		final_code = base_code
		suffix = 1
		while Company.objects.filter(code=final_code).exclude(pk=company.pk).exists():
			final_code = f"{base_code[:24]}{suffix:03d}"
			suffix += 1
		company.code = final_code
		company.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.RunPython(populate_company_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código'),
        ),
    ]
