# Generated by Django 5.2.7 on 2025-10-16 00:00

from django.db import migrations, models


def format_cnpj(digits: str) -> str:
	if len(digits) != 14:
		return digits
	return f"{digits[0:2]}.{digits[2:5]}.{digits[5:8]}/{digits[8:12]}-{digits[12:14]}"


def sync_company_codes(apps, schema_editor):
	Company = apps.get_model('companies', 'Company')
	for company in Company.objects.all():
		tax_id = (company.tax_id or '').strip()
		digits = ''.join(ch for ch in tax_id if ch.isdigit())
		if len(digits) != 14:
			continue
		update_fields = []
		if company.code != digits:
			company.code = digits
			update_fields.append('code')
		formatted = format_cnpj(digits)
		if company.tax_id != formatted:
			company.tax_id = formatted
			update_fields.append('tax_id')
		if update_fields:
			company.save(update_fields=update_fields)


class Migration(migrations.Migration):

	dependencies = [
		('companies', '0002_add_company_code'),
	]

	operations = [
		migrations.RunPython(sync_company_codes, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='company',
			name='code',
			field=models.CharField(max_length=14, unique=True, verbose_name='Código'),
		),
	]
