# Generated by Django 5.2.7 on 2025-10-18 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_code_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Desconto padrão (%)'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Desconto máximo (%)'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_agent',
            field=models.CharField(choices=[('own', 'Próprio'), ('third_party', 'Terceirizado'), ('joint', 'Compartilhado')], default='own', max_length=30, verbose_name='Agente tributário'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_regime',
            field=models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real'), ('mei', 'MEI')], default='simples', max_length=30, verbose_name='Regime tributário'),
        ),
    ]
