# Generated by Django 5.2.7 on 2025-10-23 11:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Usado em integrações e referências internas (somente letras, números e hífen).', max_length=80, unique=True, verbose_name='Identificador')),
                ('label', models.CharField(max_length=160, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Valor')),
                ('unit', models.CharField(blank=True, help_text='Ex.: %, R$, unidade etc.', max_length=32, verbose_name='Unidade')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='É percentual?')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_parameters_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parâmetro de custo',
                'verbose_name_plural': 'Parâmetros de custo',
                'ordering': ('label',),
            },
        ),
    ]
