# Generated by Django 5.2.7 on 2025-10-23 13:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0001_initial'),
        ('products', '0024_produtosync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do lote')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('default_ipi_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='IPI padrão (%)')),
                ('default_freight_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Frete padrão (%)')),
                ('mva_percent', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=6, verbose_name='MVA (%)')),
                ('st_percent', models.DecimalField(decimal_places=2, default=Decimal('24'), max_digits=6, verbose_name='Carga tributária ST (%)')),
                ('st_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.35'), max_digits=8, verbose_name='Multiplicador ST')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de custos',
                'verbose_name_plural': 'Lotes de custos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CostBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='Quantidade')),
                ('pack_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Qtd. por embal.')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Preço de compra')),
                ('ipi_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='IPI (%)')),
                ('freight_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Frete (%)')),
                ('ipi_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='IPI (R$)')),
                ('freight_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Frete (R$)')),
                ('st_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='ST (R$)')),
                ('replacement_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Custo reposição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='custos.costbatch')),
                ('supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_batch_items', to='products.supplierproductprice')),
            ],
            options={
                'verbose_name': 'Item do lote',
                'verbose_name_plural': 'Itens do lote',
                'ordering': ('code',),
                'unique_together': {('batch', 'code')},
            },
        ),
    ]
