# Generated by Django 5.2.7 on 2025-10-16 00:00

from django.db import migrations, models


def populate_salesperson_documents(apps, schema_editor):
	Salesperson = apps.get_model('sales', 'Salesperson')
	for seller in Salesperson.objects.all().order_by('pk'):
		digits = ''.join(ch for ch in ((seller.cpf or '') + (seller.code or '')) if ch.isdigit())
		if len(digits) != 11:
			digits = f"1{seller.pk:010d}"[-11:]
		seller.cpf = digits
		seller.code = digits
		seller.save(update_fields=['cpf', 'code'])


class Migration(migrations.Migration):

	dependencies = [
		('sales', '0002_salesperson'),
	]

	operations = [
		migrations.AddField(
			model_name='salesperson',
			name='cpf',
			field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
		),
		migrations.AddField(
			model_name='salesperson',
			name='code',
			field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Código'),
		),
		migrations.RunPython(populate_salesperson_documents, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='salesperson',
			name='cpf',
			field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
		),
		migrations.AlterField(
			model_name='salesperson',
			name='code',
			field=models.CharField(max_length=11, unique=True, verbose_name='Código'),
		),
	]
