# Generated by Django 5.2.7 on 2025-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesperson_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesperson',
            options={'ordering': ('user__first_name', 'user__last_name', 'user__username'), 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
