# Generated by Django 5.2.7 on 2025-10-18 20:52

import django.db.models.deletion
from django.db import migrations, models


def assign_companies(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    Quote = apps.get_model('sales', 'Quote')
    Order = apps.get_model('sales', 'Order')

    company = Company.objects.filter(is_active=True).order_by('id').first() or Company.objects.order_by('id').first()
    if not company:
        return

    Quote.objects.filter(company__isnull=True).update(company=company)
    Order.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_default_discount_percent_and_more'),
        ('sales', '0004_alter_salesperson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='quote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.RunPython(assign_companies, migrations.RunPython.noop),
    ]
