# Generated by Django 5.2.7 on 2025-10-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_company_quote_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='sales.salesperson', verbose_name='Vendedor'),
        ),
    ]
