# Generated by Django 5.2.7 on 2025-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_quote_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de entrega (dias)'),
        ),
    ]

