# Generated by Django 5.2.7 on 2026-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_loja_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='loja_codigo',
            field=models.CharField(default='000001', max_length=10, verbose_name='Código da loja'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='loja_codigo',
            field=models.CharField(default='000001', max_length=10, verbose_name='Código da loja'),
        ),
    ]
