# Generated by Django 5.2.7 on 2025-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientesync'),
        ('companies', '0004_company_default_discount_percent_and_more'),
        ('sales', '0012_add_loja_codigo_to_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loja_codigo',
            field=models.CharField(default='00001', max_length=10, verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='loja_codigo',
            field=models.CharField(default='00001', max_length=10, verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='quote',
            name='loja_codigo',
            field=models.CharField(default='00001', max_length=10, verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='loja_codigo',
            field=models.CharField(default='00001', max_length=10, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('number', 'loja_codigo'), name='uniq_sales_order_number_loja'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('number', 'loja_codigo'), name='uniq_sales_quote_number_loja'),
        ),
    ]
