# Generated by Django 5.2.7 on 2025-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_trigram_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_product_code'),
        ),
    ]
