# Generated by Django 5.2.7 on 2025-10-16 07:32

from django.db import migrations, models
from django.db.models import Q, F


def copy_supplier_code_to_reference(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(
        Q(reference__isnull=True) | Q(reference='')
    ).exclude(
        Q(supplier_code__isnull=True) | Q(supplier_code='')
    ).update(reference=F('supplier_code'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_unique_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('reference', 'supplier_code', '-created_at'), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(copy_supplier_code_to_reference, noop),
    ]
