# Generated by Django 5.2.7 on 2025-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0007_alter_product_options_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='products', to='companies.company'),
        ),
    ]
