# Generated by Django 5.2.7 on 2025-10-16 00:00

from django.db import migrations, models
import django.utils.timezone


def populate_supplier_documents(apps, schema_editor):
	Supplier = apps.get_model('products', 'Supplier')
	for supplier in Supplier.objects.all().order_by('pk'):
		doc_sources = (supplier.document or '') + (supplier.code or '')
		doc_digits = ''.join(ch for ch in doc_sources if ch.isdigit())
		if len(doc_digits) == 14:
			person_type = 'J'
		elif len(doc_digits) == 11:
			person_type = 'F'
		else:
			person_type = 'J'
			doc_digits = f"9{supplier.pk:013d}"[-14:]
		supplier.person_type = person_type
		supplier.document = doc_digits
		supplier.code = doc_digits
		supplier.save(update_fields=['person_type', 'document', 'code'])


class Migration(migrations.Migration):

	dependencies = [
		('products', '0009_product_pricing_base_cost_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='supplier',
			name='person_type',
			field=models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='J', max_length=1, verbose_name='Tipo de pessoa'),
		),
		migrations.AddField(
			model_name='supplier',
			name='document',
			field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ'),
		),
		migrations.AddField(
			model_name='supplier',
			name='created_at',
			field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='supplier',
			name='updated_at',
			field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Atualizado em'),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='supplier',
			name='code',
			field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código'),
		),
		migrations.RunPython(populate_supplier_documents, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='supplier',
			name='document',
			field=models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ'),
		),
		migrations.AlterField(
			model_name='supplier',
			name='code',
			field=models.CharField(max_length=14, unique=True, verbose_name='Código'),
		),
	]
