# Generated by Django 5.2.7 on 2025-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_supplier_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
