# Generated by Django 5.2.7 on 2025-10-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_supplier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='productgroup',
            unique_together={('parent_group', 'name')},
        ),
    ]
