# Generated by Django 5.2.7 on 2025-10-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_supplier_address_supplier_city_supplier_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_fractional_sale',
            field=models.BooleanField(default=False, verbose_name='Permite venda fracionada'),
        ),
    ]
