# Generated by Django 5.2.7 on 2025-10-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_generic_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceadjustmentitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('skipped', 'Ignorado')], default='pending', max_length=20),
        ),
    ]
