# Generated by Django 5.2.7 on 2025-10-18 20:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def bootstrap_product_stock(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductStock = apps.get_model('products', 'ProductStock')
    Company = apps.get_model('companies', 'Company')

    default_company = Company.objects.filter(is_active=True).order_by('id').first() or Company.objects.order_by('id').first()
    if not default_company:
        return

    for product in Product.objects.all():
        quantity = product.stock or Decimal('0.00')
        linked_companies = list(product.companies.filter(is_active=True).order_by('id'))
        if not linked_companies:
            linked_companies = [default_company]
        primary = linked_companies[0]
        ProductStock.objects.update_or_create(
            product=product,
            company=primary,
            defaults={'quantity': quantity},
        )
        for company in linked_companies[1:]:
            ProductStock.objects.update_or_create(
                product=product,
                company=company,
                defaults={'quantity': Decimal('0.00')},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_default_discount_percent_and_more'),
        ('products', '0022_alter_priceadjustmentitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Quantidade')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Estoque mínimo')),
                ('max_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Estoque máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Estoque por empresa',
                'verbose_name_plural': 'Estoques por empresa',
                'ordering': ('product__name', 'company__name'),
                'unique_together': {('product', 'company')},
            },
        ),
        migrations.RunPython(bootstrap_product_stock, migrations.RunPython.noop),
    ]
