# Generated by Django 5.2.7 on 2025-10-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoSync',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estoque_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('row_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_produtos',
                'managed': False,
            },
        ),
    ]
