# Generated by Django 5.2.7 on 2025-10-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_default_discount_percent_and_more'),
        ('products', '0024_produtosync'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price_company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_price_products', to='companies.company', verbose_name='Empresa do último custo'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Atualizado custo em'),
        ),
    ]
