# Generated by Django 5.2.7 on 2025-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_cost_price_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plu_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código PLU'),
        ),
    ]
