# Generated by Django 5.2.7 on 2025-12-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_erp_produtos_sync_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produtosync',
            table='vw_produtos_sync_preco_estoque',
        ),
    ]
