# Generated by Django 5.2.7 on 2025-12-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_refresh_produtos_sync_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produtosync',
            table='erp_produtos_sync',
        ),
    ]
